name: Sentiment Analysis API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install
          git lfs pull

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn requests pytest textblob transformers torch sentencepiece

      - name: Cache Hugging Face models
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: hf-models

      - name: Pre-download Hugging Face model
        run: |
          python -c "from transformers import pipeline; pipeline('sentiment-analysis')"

      - name: Run FastAPI server
        run: |
          sudo kill -9 $(sudo lsof -t -i:8000) || true
          netstat -tulnp | grep 8000 | awk '{print $7}' | cut -d'/' -f1 | xargs kill -9 || true
          uvicorn main:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
          sleep 10

      - name: Run tests
        run: |
          pytest test_api.py -v